### ISSUE TITLE
Travid CI is failing

### ISSUE THREAD

**Issue by azielke** [clutterbox/ansible-dehydrated#13]
Molecule 3 had some breaking changes.

At least the lint-Key must be changed to a string.

Edit: Seems easy to fix: https://molecule.readthedocs.io/en/latest/configuration.html#lint

**Comment by eengstrom** [comment]
So, I have a fix for the lint issue, but not all of the molecule tests will pass; issues remaining:

 - can't install `lexicon-dns` on debian 8 (required version of python, I think)
 - can't install cron job (either disable that for testing, or setup cron in containers)

Do you want a PR for just the lint, or all of the issues?

**Comment by eengstrom** [comment]
PR #14 will fix all outstanding issues, including the two I mentioned in the previous comment.
